openapi: 3.0.0
info:
  version: 0.0.1
  title: sktime forecast
servers:
  - url: 'http://localhost:3000'
paths:
  /forecast:
    post:
      description:
        Sending time series which needs to be forecasted
      operationId: app.naive_forecast
      requestBody:
        required: true
        content: 
            application/json:
              schema:
                    properties: 
                       time_series:
                         type: array
                         items:
                           type: number 
      responses:
        '200':
          description: response with time series forecast
          content:
            application/json:
              schema:
                properties: 
                    forecast:
                      type: array 
                      items:
                        type: number
        
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas: 
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          